// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFYBdBo6DwrVc_pHrnC73KZyxk3uwVM34',
    appId: '1:386131382515:web:20257c79c4dfed2ad16786',
    messagingSenderId: '386131382515',
    projectId: 'social-media-app-3cc43',
    authDomain: 'social-media-app-3cc43.firebaseapp.com',
    storageBucket: 'social-media-app-3cc43.appspot.com',
    measurementId: 'G-B880WR4VS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKcP6_QKfGgyH6k1a4oDkATunai21cq4',
    appId: '1:386131382515:android:e2c26128d13f9ee1d16786',
    messagingSenderId: '386131382515',
    projectId: 'social-media-app-3cc43',
    storageBucket: 'social-media-app-3cc43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbLDm26BA2ynBPSnRkd3bu2mzi91e22jM',
    appId: '1:386131382515:ios:e452f569b554423fd16786',
    messagingSenderId: '386131382515',
    projectId: 'social-media-app-3cc43',
    storageBucket: 'social-media-app-3cc43.appspot.com',
    iosClientId:
        '386131382515-kq3lnmkj47a2gqfcsasnkhvodg1lcvie.apps.googleusercontent.com',
    iosBundleId: 'com.chattyevent.chattyevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbLDm26BA2ynBPSnRkd3bu2mzi91e22jM',
    appId: '1:386131382515:ios:cd2628e1c3a03f15d16786',
    messagingSenderId: '386131382515',
    projectId: 'social-media-app-3cc43',
    storageBucket: 'social-media-app-3cc43.appspot.com',
    iosClientId:
        '386131382515-ldg5dg50ka8fnj2g727b7l5b0ps973f8.apps.googleusercontent.com',
    iosBundleId: 'com.chattyEvent.chattyEvent',
  );
}
